# Generated by Django 3.0.3 on 2020-02-15 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Product Name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Product Quantity')),
                ('sku', models.CharField(max_length=50, verbose_name='Stock Keeping Unit')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Warehouse name')),
                ('location', models.CharField(max_length=300, verbose_name='Warehouse Location')),
            ],
        ),
    ]
