# Generated by Django 3.0.3 on 2020-02-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200215_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='user',
        ),
    ]
