# Generated by Django 3.0.3 on 2020-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200216_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(default=1, max_length=100, verbose_name='Destination of Shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Product Quantity'),
            preserve_default=False,
        ),
    ]
