# Generated by Django 3.0.3 on 2020-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200216_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='Unit Price'),
            preserve_default=False,
        ),
    ]
