# Generated by Django 3.0.3 on 2020-02-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved user'),
        ),
    ]
