# Generated by Django 3.0.3 on 2020-03-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
